<?php

/** @var Article[] $articles */

use Blog\Entity\Article;

$title = 'Gestion du Blog';
$this->headTitle($title);

?>

<?php echo $this->partial('partial/flashmessenger') ?>

<div class="row">
    <div class="box">

        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline pull-right">
                    <li>
                        <a href="<?php echo $this->url('article', array('action' => 'add')) ?>" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span> Ajouter un article
                        </a>
                    </li>
                </ul>
                <h4><?php echo $title ?></h4>
            </div>
        </div>

        <hr class="long-hr"/>

        <div class="row">
            <div class="col-lg-12">

                <?php if (count($articles)) : ?>

                    <table class="table">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Titre</th>
                            <th>Date</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($articles as $article) : ?>
                            <tr>
                                <td>
                                    <?php if ($article->getMainPicture()) : ?>
                                        <?php $picture = $article->getMainPicture() ?>
                                        <img src="<?php echo $this->url('picture', array('action' => 'images', 'id' => $article->getId(), 'name' => $picture->getThumbnail())) ?>"
                                             alt="<?php $article->getCompleteTitle() ?>" class="img-responsive img-left">
                                    <?php endif ?>
                                </td>
                                <td>
                                    <a class="silent"
                                       href="<?php echo $this->url('article', array('action' => 'edit', 'id' => $article->getId())) ?>">
                                        <?php echo $article->getCompleteTitle() ?>
                                    </a>
                                </td>
                                <td><?php echo $article->getDateString() ?></td>
                                <td>
                                    <ul class="list-inline pull-right">
                                        <li>
                                            <a href="<?php echo $this->url('article', array('action' => 'detail', 'id' => $article->getId())) ?>"
                                               class="btn btn-xs btn-primary">
                                                <span class="glyphicon glyphicon-eye-open"></span> Ouvrir
                                           </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('article', array('action' => 'edit', 'id' => $article->getId())) ?>"
                                               class="btn btn-xs btn-warning">
                                                <span class="glyphicon glyphicon-pencil"></span> Modifier
                                           </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('article', array('action' => 'delete', 'id' => $article->getId())) ?>"
                                               class="btn btn-xs btn-danger">
                                                <span class="glyphicon glyphicon-trash"></span> Supprimer
                                           </a>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        <?php endforeach ?>
                        </tbody>
                    </table>

                <?php else : ?>

                    <p class="center-text">
                        Aucun article !
                    </p>

                <?php endif ?>

            </div>
        </div>

    </div>
</div>