<?php

/**
 * @var Blog\Form\ArticleForm $form
 * @var string $autocompleteTagSource
 */

$title = 'Ajouter un Article';
$this->headTitle($title);

$form->prepare();

?>

<?php echo $this->partial('partial/flashmessenger') ?>

<div class="row">
    <div class="box">

        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline pull-right">
                    <li>
                        <a href="<?php echo $this->url('manage') ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-chevron-left"></span>Retour
                        </a>
                    </li>
                </ul>
                <h4><?php echo $title ?></h4>
            </div>
        </div>

        <hr class="long-hr"/>

        <div class="row">
            <div class="col-lg-12">

                <?php echo $this->form()->openTag($form) ?>

                <div class="row">
                    <div class="col-lg-offset-3 col-lg-6">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('title')) ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-offset-3 col-lg-6">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('subtitle')) ?>
                        </div>
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('category')) ?>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('tagsString')) ?>
                        </div>
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('youtube')) ?>
                        </div>
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-lg-8">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('text')) ?>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('textPosition')) ?>
                        </div>
                    </div>
                </div>
                <hr class="long-hr"/>

                <div class="form-group">
                    <ul class="list-inline pull-right">
                        <li>
                            <a href="<?php echo $this->url('manage') ?>" class="btn btn-default">
                                Annuler
                            </a>
                        </li>
                        <li>
                            <?php echo $this->formHidden($form->get('id')) ?>
                            <?php echo $this->formRow($form->get('submit')) ?>
                        </li>
                    </ul>
                </div>

                <?php echo $this->form()->closeTag($form) ?>

            </div>
        </div>

    </div>
</div>

<script>
    $('#tagsString').tagEditor({
        autocomplete: {
            delay: 1,
            position: { collision: 'flip' },
            source: <?php echo $autocompleteTagSource ?>
        },
        delimiter: ' ',
        placeholder: 'Choisis tes #tags ...'
    });
</script>