<?php

/**
 * @var Blog\Form\ArticleForm $form
 */

$title = 'Ajouter un Article';
$this->headTitle($title);

?>

<?php echo $this->partial('partial/flashmessenger') ?>

<div class="row">
    <div class="box">

        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline pull-right">
                    <li>
                        <a href="<?php echo $this->url('manage') ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-chevron-left"></span>Retour
                        </a>
                    </li>
                </ul>
                <h4><?php echo $title ?></h4>
            </div>
        </div>

        <hr class="long-hr"/>

        <div class="row">
            <div class="col-lg-12">

                <?php echo $this->form()->openTag($form) ?>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('title')) ?>
                </div>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('subtitle')) ?>
                </div>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('text')) ?>
                </div>

                <div class="form-group">
                    <ul class="list-inline pull-right">
                        <li>
                            <a href="<?php echo $this->url('manage') ?>" class="btn btn-default">
                                Annuler
                            </a>
                        </li>
                        <li>
                            <?php echo $this->formHidden($form->get('id')) ?>
                            <?php echo $this->formRow($form->get('submit')) ?>
                        </li>
                    </ul>
                </div>

                <?php echo $this->form()->closeTag($form) ?>

            </div>
        </div>

    </div>
</div>