<?php

/**
 * @var Blog\Entity\Article $article
 * @var Blog\Entity\Tag $tag
 */

$title = $article->getTitle();
$subtitle = $article->getSubtitle();
$this->headTitle($title);

?>

<?php echo $this->partial('partial/flashmessenger') ?>

<div class="row">
    <div class="box">
        <div class="row">
            <div class="col-lg-2">
            </div>
            <div class="col-lg-8 text-center">
                <hr class="short-hr"/>
                <h2><?php echo $title ?></h2>
                <h3 class="intro-subtext"><?php echo $subtitle ?></h3>
                <hr class="short-hr"/>
            </div>
            <div class="col-lg-2">
                <?php if (!is_null($this->identity())) : ?>
                    <ul class="list-inline pull-right">
                        <li>
                            <a href="<?php echo $this->url('article', array('action' => 'edit', 'id' => $article->getId())) ?>">
                                <span class="glyphicon glyphicon-pencil text-warning"></span>
                            </a>
                        </li>
                    </ul>
                    <br/>
                    <br/>
                <?php endif ?>
                <ul class="list-unstyled pull-right text-right">
                    <?php foreach ($article->getTags() as $tag) : ?>
                        <li>
                            <h4>
                                <a href="#" style="text-decoration: none">
                                    <span class="label label-info">#<?php echo $tag->getTitle() ?></span>
                                </a>
                            </h4>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <p class="text-<?php echo $article->getTextPosition1() ?>">
                    <?php echo $article->getText1() ?>
                </p>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-lg-12">
                <img class="img-responsive img-polaroid-border img-<?php echo $article->getPhotoPosition1() ?>"
                     alt="<?php echo $article->getCompleteTitle() ?>"
                     style="max-width: 100%"
                     src="<?php echo $this->basePath('/img/articles/'.$article->getPhoto1()) ?>">
                <hr class="visible-xs">

                <?php if ($article->getText2()) : ?>
                    <p class="text-<?php echo $article->getTextPosition2() ?>">
                        <br/><?php echo $article->getText2() ?>
                    </p>
                <?php endif ?>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-lg-12">
                <?php if ($article->getPhoto2()) : ?>
                    <img class="img-responsive img-polaroid-border img-<?php echo $article->getPhotoPosition2() ?>"
                         alt="<?php echo $article->getCompleteTitle() ?>"
                         style="max-width: 600px"
                         src="<?php echo $this->basePath('/img/articles/'.$article->getPhoto2()) ?>">
                    <hr class="visible-xs">
                <?php endif ?>

                <?php if ($article->getText3()) : ?>
                    <p class="text-<?php echo $article->getTextPosition3() ?>">
                        <br/><?php echo $article->getText3() ?>
                    </p>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>