<?php

/** @var Blog\Entity\Article $article */

$title = $article->getTitle();
$subtitle = $article->getSubtitle();
$this->headTitle($title);

?>

<?php echo $this->partial('partial/flashmessenger') ?>

<div class="row">
    <div class="box">
        <div class="row">
            <div class="col-lg-2">
                <ul class="list-inline">
                    <li>
                        <a href="<?php echo $this->url('blog') ?>">
                            <span class="glyphicon glyphicon-chevron-left text-muted"></span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-8 text-center">
                <hr class="short-hr"/>
                <h2><?php echo $title ?></h2>
                <h3 class="intro-subtext"><?php echo $subtitle ?></h3>
                <hr class="short-hr"/>
            </div>
            <div class="col-lg-2">
                <ul class="list-inline pull-right">
                    <li>
                        <a href="<?php echo $this->url('article', array('action' => 'edit', 'id' => $article->getId())) ?>">
                            <span class="glyphicon glyphicon-pencil text-warning"></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <img class="img-responsive img-border img-<?php echo $article->getPhotoPosition() ?>" alt="<?php echo $article->getCompleteTitle() ?>"
                     style="max-width: 600px"
                     src="<?php echo $this->basePath('/img/articles/'.$article->getPhoto()) ?>">
                <hr class="visible-xs">

                <p><br/><?php echo $article->getText() ?></p>
            </div>
        </div>
    </div>
</div>