<?php

/**
 * @var Blog\Entity\Article $article
 * @var Blog\Entity\Article $articleRecent
 * @var Blog\Entity\Article $articleAncien
 * @var Blog\Entity\Picture $picture
 * @var Blog\Entity\Tag $tag
 */

$title = $article->getTitle();
$subtitle = $article->getSubtitle();
$this->headTitle($title);

?>

<br>
<?php echo $this->partial('partial/flashmessenger') ?>

<div class="row">
    <div class="box">
        <div class="row">
            <div class="col-lg-2">
            </div>
            <div class="col-lg-8 text-center">
                <h2><?php echo $title ?></h2>
                <h3 class="intro-subtext"><?php echo $subtitle ?></h3>
                <hr class="short-hr"/>
            </div>
            <div class="col-lg-2">
                <?php if (!is_null($this->identity())) : ?>
                    <ul class="list-inline pull-right">
                        <li>
                            <a href="<?php echo $this->url('article', array('action' => 'edit', 'id' => $article->getId())) ?>">
                                <span class="glyphicon glyphicon-pencil text-warning"></span>
                            </a>
                        </li>
                    </ul>
                    <br/>
                    <br/>
                <?php endif ?>
                <ul class="list-unstyled pull-right text-right">
                    <?php foreach ($article->getTags() as $tag) : ?>
                        <li>
                            <h4>
                                <a href="<?php echo $this->url('tags', array('names' => $tag->getTitle())) ?>" style="text-decoration: none">
                                    <span class="label label-info">#<?php echo $tag->getTitle() ?></span>
                                </a>
                            </h4>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
        <?php if ($article->getText()) : ?>
            <div class="row">
                <div class="col-lg-12">
                    <p class="text-center">
                        <?php echo nl2br($article->getText()) ?>
                    </p>
                </div>
            </div>
            <br/>
        <?php endif ?>
        <?php if (!$article->getYoutube()) : ?>
            <?php if ($article->isMosaique()) : ?>
                <div class="row hidden-xs hidden-sm">
                    <div class="col-lg-4">
                        <?php
                        foreach ($article->getPictures() as $key => $picture) {
                            if ($key % 3 == 0) {
                                echo $this->partial('blog/article/partial/tile', array('picture' => $picture));
                            }
                        }
                        ?>
                    </div>
                    <div class="col-lg-4">
                        <?php
                        foreach ($article->getPictures() as $key => $picture) {
                            if ($key % 3 == 1) {
                                echo $this->partial('blog/article/partial/tile', array('picture' => $picture));
                            }
                        }
                        ?>
                    </div>
                    <div class="col-lg-4">
                        <?php
                        foreach ($article->getPictures() as $key => $picture) {
                            if ($key % 3 == 2) {
                                echo $this->partial('blog/article/partial/tile', array('picture' => $picture));
                            }
                        }
                        ?>
                    </div>
                </div>
                <div class="row hidden-md hidden-lg">
                    <div class="col-sm-6">
                        <?php
                        foreach ($article->getPictures() as $key => $picture) {
                            if ($key % 3 == 0) {
                                echo $this->partial('blog/article/partial/tile', array('picture' => $picture));
                            }
                        }
                        ?>
                    </div>
                    <div class="col-sm-6">
                        <?php
                        foreach ($article->getPictures() as $key => $picture) {
                            if ($key % 3 == 1) {
                                echo $this->partial('blog/article/partial/tile', array('picture' => $picture));
                            }
                        }
                        ?>
                    </div>
                </div>
            <?php else : ?>
                <?php foreach ($article->getPictures() as $picture) : ?>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="image">
                                <a class="fancybox" href="<?php echo $picture->getFlickrUrl() ?>" rel="gallery"
                                   title="<?php echo $picture->getLegend() ?>">
                                    <img class="img-responsive img-center"
                                         alt="<?php echo $picture->getLegend() ?>"
                                         src="<?php echo $picture->getFlickrUrl() ?>">
                                </a>
                            </div>
                            <?php if ($picture->getLegend()) : ?>
                                <p class="text-center">
                                    <br/><?php echo nl2br($picture->getLegend()) ?>
                                </p>
                            <?php endif ?>
                        </div>
                    </div>
                    <br/>
                <?php endforeach ?>
            <?php endif ?>
        <?php else : ?>
            <div class="row">
                <div class="col-lg-12">
                    <div class="embed-responsive embed-responsive-4by3">
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<?php echo $article->getYoutube() ?>" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
            <br/>
        <?php endif ?>

        <!-- NAVIGATION -->
        <hr class=""/>
        <div class="row">
            <div class="col-lg-6">
                <?php if (!is_null($articleRecent)) : ?>
                    <a class="inbox-link" href="<?php echo $this->url('article', array('action' => 'detail', 'id' => $articleRecent->getId())) ?>">
                        << <?php echo $articleRecent->getTitle() ?>
                    </a>
                <?php endif ?>
            </div>
            <div class="col-lg-6">
                <?php if (!is_null($articleAncien)) : ?>
                    <a class="inbox-link pull-right" href="<?php echo $this->url('article', array('action' => 'detail', 'id' => $articleAncien->getId())) ?>">
                        <?php echo $articleAncien->getTitle() ?> >>
                    </a>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>
<br><br>
<script>
</script>