<?php
/**
 * @var \Blog\Entity\Article $article
 * @var \Blog\Entity\Picture $picture
 * @var \Blog\Form\PictureForm $form
 * @var array $displayedCollection
 */

$title = $this->translate('Edition des Photos');
$this->headTitle($title);

$form->prepare();
?>

<br>
<?php echo $this->partial('partial/flashmessenger') ?>

<div class="row">
    <div class="box">

        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline pull-right">
                    <li>
                        <a href="<?php echo $this->url('manage') ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-chevron-left"></span>Retour
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('article', array('action' => 'edit', 'id' => $article->getId())) ?>"
                           class="btn btn-primary">
                            <span class="glyphicon glyphicon-pencil"></span>
                            Modifier l'article
                        </a>
                    </li>
                </ul>
                <h4><?php echo $title ?></h4>
            </div>
        </div>

        <hr class="short-hr"/>

        <div class="row">
            <div class="col-lg-12">
                <?php echo $this->form()->openTag($form) ?>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Ajouter</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <?php echo $this->formRow($form->get('flickrUrl')) ?>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <?php echo $this->formRow($form->get('legend')) ?>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <br>
                                <div class="form-group">
                                    <ul class="list-inline pull-right">
                                        <li>
                                            <a href="<?php echo $this->url('manage') ?>" class="btn btn-default">
                                                Annuler
                                            </a>
                                        </li>
                                        <li>
                                            <?php echo $this->formRow($form->get('submit')) ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo $this->form()->closeTag() ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <?php if ($article->getPictures()->count()) : ?>
                    <ul id="sortable" class="list-group">
                        <?php foreach ($article->getPictures() as $picture) : ?>
                            <li class="list-group-item" id="<?php echo $picture->getId() ?>">
                                <img src="<?php echo $picture->getFlickrUrl() ?>" width="100" height="100"
                                     alt="<?php $picture->getLegend() ?>" class="img-rounded">
                                &emsp;<?php echo $picture->getLegend() ?>
                                <ul class="list-inline pull-right">
                                    <li>
                                        <a href="<?php echo $this->url('picture', array('action' => 'edit', 'id' => $picture->getId()))?>"
                                           title="Modifier">
                                            <span class="glyphicon glyphicon-pencil text-warning"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->url('article', array('action' => 'delete-picture', 'id' => $article->getId(), 'picture' => $picture->getId()))?>"
                                           title="Supprimer">
                                            <span class="glyphicon glyphicon-trash text-danger"></span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        <?php endforeach ?>
                    </ul>
                <?php else : ?>
                    <div class="alert alert-warning" role="alert">
                        <span class="glyphicon glyphicon-exclamation-sign"></span>
                        Il n'y a pas encore de photo.
                    </div>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>

<script>
    $("#sortable").sortable({
        stop: sortableStop
    });
    function sortableStop() {
        var sortedIDs = $("#sortable").sortable("toArray");
        $("body").css("cursor", "progress");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->url('article', array('action' => 'ajax-reorder-pictures')) ?>",
            data: {
                id: <?php echo $article->getId() ?>,
                sortedIDs: sortedIDs
            },
            success: function(data) {
                if (!data) {
                    alert('Une erreur est survenue.');
                }
                $("body").css("cursor", "default");
            },
            error: function() {
                alert('Une erreur est survenue.');
                $("body").css("cursor", "default");
            }
        });
    }
</script>
