<?php
/**
 * @var \Blog\Entity\Article $article
 * @var \Blog\Entity\Picture $picture
 * @var \Blog\Form\PictureForm $form
 * @var array $displayedCollection
 */

$title = $this->translate('Edition des Photos');
$this->headTitle($title);

$form->prepare();
?>

<?php echo $this->partial('partial/flashmessenger') ?>

<div class="row">
    <div class="box">

        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline pull-right">
                    <li>
                        <a href="<?php echo $this->url('manage') ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-chevron-left"></span>Retour
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('article', array('action' => 'edit', 'id' => $article->getId())) ?>"
                           class="btn btn-primary">
                            <span class="glyphicon glyphicon-pencil"></span>
                            Modifier l'article
                        </a>
                    </li>
                </ul>
                <h4><?php echo $title ?></h4>
            </div>
        </div>

        <hr class="long-hr"/>

        <div class="row">
            <div class="col-lg-5">
                <?php if ($article->getPictures()->count() == 0) : ?>
                    <div class="alert alert-warning" role="alert">
                        <span class="glyphicon glyphicon-exclamation-sign"></span>
                        Il n'y a pas encore de bloc photo.
                    </div>
                <?php endif ?>
                <?php foreach ($article->getPictures() as $picture) : ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <ul class="list-inline pull-right">
                                <li>
                                    <a href="<?php echo $this->url('picture', array('action' => 'edit', 'id' => $picture->getId()))?>"
                                       title="Modifier">
                                        <span class="glyphicon glyphicon-pencil text-warning"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('article', array('action' => 'delete-picture', 'id' => $article->getId(), 'picture' => $picture->getId()))?>"
                                       title="Supprimer">
                                        <span class="glyphicon glyphicon-trash text-danger"></span>
                                    </a>
                                </li>
                            </ul>
                            <h3 class="panel-title"><?php echo $picture->getLegend() ?></h3>
                        </div>
                        <img src="<?php echo $this->url('picture', array('action' => 'images', 'id' => $article->getId(), 'name' => $picture->getFilename())) ?>"
                             alt="<?php $picture->getLegend() ?>" class="img-responsive">
                        <table class="table">
                            <tbody>
                            <tr>
                                <th>Légende</th>
                                <td><?php echo $picture->getLegend() ?></td>
                            </tr>
                            <tr>
                                <th>Position</th>
                                <td><?php echo $picture->getPositionLabel() ?></td>
                            </tr>
                            <tr>
                                <th>Texte</th>
                                <td><?php echo $picture->getText() ?></td>
                            </tr>
                            <tr>
                                <th>Position texte</th>
                                <td><?php echo $picture->getTextPositionLabel() ?></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                <?php endforeach ?>
            </div>

            <div class="col-lg-7">

                <?php echo $this->form()->openTag($form) ?>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Ajouter</h3>
                    </div>
                    <div class="panel-body">
                        <?php if ($form->hasError()) : ?>
                            <div class="alert alert-warning">
                                <span class="glyphicon glyphicon-exclamation-sign"></span>
                                Une erreur est survenue. Je pense à recharger le fichier.
                            </div>
                        <?php endif ?>

                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="control-label">
                                    <span>
                                        <?php echo $form->get('filename')->getLabel() ?>
                                    </span>
                                        <canvas id="canvas" class="img-thumbnail form-control<?php
                                        echo (sizeof($form->get('filename')->getMessages()) > 0) ? ' input-error' : '' ?>"
                                                width="140" height="140" style="height: 140px!important; width: 140px!important;">
                                        </canvas>
                                        <?php echo $this->formFile($form->get('filename')) ?>
                                    </label>
                                    <?php if (sizeof($form->get('filename')->getMessages()) > 0) : ?>
                                        <ul class="text-danger">
                                            <?php foreach ($form->get('filename')->getMessages() as $message) : ?>
                                                <li>
                                                    <?php echo $message ?>
                                                </li>
                                            <?php endforeach ?>
                                        </ul>
                                    <?php endif ?>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formRow($form->get('legend')) ?>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formRow($form->get('position')) ?>
                                </div>
                            </div>

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <?php echo $this->formRow($form->get('text')) ?>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formRow($form->get('textPosition')) ?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <ul class="list-inline pull-right">
                                        <li>
                                            <a href="<?php echo $this->url('manage') ?>" class="btn btn-default">
                                                Annuler
                                            </a>
                                        </li>
                                        <li>
                                            <?php echo $this->formRow($form->get('submit')) ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function() {
        /** A chaque changement d'état de l'input, change la miniature **/
        $('input[type=file]').change(function(e){
            var canvas = $(this).parent().find('canvas');
            var ctx = canvas[0].getContext('2d');
            var image = new Image();
            image.onload = function() {
                if(image.height > 140) {
                    image.width *= 140 / image.height;
                    image.height = 140;
                } else if(image.width > 140) {
                    image.height *= 140 / image.width;
                    image.width = 140;
                }
                ctx.clearRect(0, 0, 140, 140);
                ctx.drawImage(image, 0, 0, 140, 140);
            };
            image.src = URL.createObjectURL(e.target.files[0]);
        });
    });
</script>
