<?php echo $this->doctype() ?>
<html lang="fr">
<head>
    <meta charset="utf-8">

    <?php
    echo $this->headTitle();
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    ?>

    <!-- Scripts -->
    <?php
    echo $this->headScript()
        ->prependFile($this->basePath('/js/geays-globe.js'))
        ->prependFile($this->basePath('/js/bootstrap-switch.min.js'))
        ->prependFile($this->basePath('/js/jquery.mousewheel.pack.js'))
        ->prependFile($this->basePath('/css/jquery.fancybox.pack.js'))
        ->prependFile($this->basePath('/js/tagEditor/jquery.caret.min.js'))
        ->prependFile($this->basePath('/js/tagEditor/jquery.tag-editor.min.js'))
        ->prependFile($this->basePath('/js/bootstrap/bootstrap.min.js'))
        ->prependFile($this->basePath('/js/jquery-ui.min.js'))
        ->prependFile($this->basePath('/js/bootstrap/jquery.js'))
    ;
    ?>

    <!-- Styles -->
    <?php
        echo $this->headLink(
            array(
                'rel' => 'icon',
                'type' => 'image/png',
                'href' => $this->basePath('/img/gg-favicon-white.png'),
            )
        )
        ->prependStylesheet($this->basePath('/css/jquery.fancybox.css'))
        ->prependStylesheet($this->basePath('/css/bootstrap-switch.min.css'))
        ->prependStylesheet($this->basePath('/css/magnific-popup.css'))
        ->prependStylesheet($this->basePath('/css/geay-globe.css'))
        ->prependStylesheet($this->basePath('/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/css/jquery.tag-editor.css'))
        ->prependStylesheet($this->basePath('/css/jquery-ui.min.css'))
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Condensed:300,400,700')
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800')
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic')
        ;

    ?>
</head>
<body>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-36436204-2', 'auto');
    ga('send', 'pageview');

</script>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-clean" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <a class="navbar-brand yellowtitle" href="<?php echo $this->url('home') ?>">Geay's Globe</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="<?php echo $this->navigation('navigation')->findById('home')->isActive(true) ? 'active' : '' ?>">
                    <a href="<?php echo $this->url('home') ?>" class="button border-fade">Accueil</a>
                </li>
                <li class="<?php echo $this->navigation('navigation')->findById('histo')->isActive(true) ? 'active' : '' ?>">
                    <a href="<?php echo $this->url('histo') ?>">Historique</a>
                </li>
                <li class="<?php echo $this->navigation('navigation')->findById('tags')->isActive(true) ? 'active' : '' ?>">
                    <a href="<?php echo $this->url('tags') ?>">#TAGS</a>
                </li>
                <li class="<?php echo $this->navigation('navigation')->findById('contact')->isActive(true) ? 'active' : '' ?>">
                    <a href="<?php echo $this->url('contact') ?>">Contact</a>
                </li>
            <?php if (!is_null($this->identity())) : ?>
                <li class="<?php echo $this->navigation('navigation')->findById('manage')->isActive(true) ? 'active' : '' ?>">
                    <a href="<?php echo $this->url('manage', array('action' => 'index')) ?>">Gestion</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('logout') ?>">
                        <span class="text-danger">Exit</span>
                    </a>
                </li>
            <?php endif ?>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Introduction -->
<div class="intro-xs visible-xs-block">
    <div class="container">
    </div>
</div>
<div class="intro-sm visible-sm-block">
    <div class="container">
    </div>
</div>
<div class="intro-md visible-md-block">
    <div class="container">
    </div>
</div>
<div class="intro-lg visible-lg-block">
    <div class="container">
    </div>
</div>

<div class="container">
    <?php echo $this->content ?>
</div>

</body>
</html>
