<?php echo $this->doctype(); ?>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('GG')->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

        <!-- Les styles -->
        <?php
        echo $this->headLink(
                array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath('/img/favicon.ico')
                )
            )
            ->prependStylesheet($this->basePath('/css/signin.min.css'))
            ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic');
        ?>

        <!-- Les scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('/js/signin.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',)) ?>
    </head>
    <body>
    <div class="container-fluid">
        <div class="signin">
            <div class="row">
                <div class="logo">
                    <img src="<?php echo $this->basePath('/img/logo-gg.png'); ?>" alt="Geay Globe"/>
                </div>
            </div>
            <?php echo $this->content ?>
        </div>
    </div>
    </body>
</html>