<?php
/**
 * @var \Blog\Entity\Picture $picture
 * @var \Blog\Form\PictureForm $form
 * @var array $displayedCollection
 */

$title = $this->translate('Modifier une Photo');
$this->headTitle($title);

$articleId = $picture->getArticle()->getId();
$form->prepare();
?>

<br>
<?php echo $this->partial('partial/flashmessenger') ?>

<div class="row">
    <div class="box col-lg-offset-2 col-lg-8">

        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline pull-right">
                    <li>
                        <a href="<?php echo $this->url('article', array('action' => 'edit-pictures', 'id' => $articleId)) ?>"
                           class="btn btn-default">
                            <span class="glyphicon glyphicon-chevron-left"></span>Retour
                        </a>
                    </li>
                </ul>
                <h4><?php echo $title ?></h4>
            </div>
        </div>

        <hr class="short-hr"/>

        <div class="row">
            <div class="col-lg-12">

                <?php echo $this->form()->openTag($form) ?>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('flickrUrl')) ?>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('legend')) ?>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <br>
                        <div class="form-group">
                            <ul class="list-inline pull-right">
                                <li>
                                    <a href="<?php echo $this->url('article', array('action' => 'edit-pictures', 'id' => $articleId)) ?>"
                                       class="btn btn-default">
                                        Annuler
                                    </a>
                                </li>
                                <li>
                                    <?php echo $this->formRow($form->get('submit')->setValue('Modifier')) ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
    </div>
</div>
