<?php

/**
 * @var Doctrine\Common\Collections\ArrayCollection $articles
 * @var Blog\Entity\Article $article
 */

$title = 'Accueil';
$this->headTitle($title);

?>

<div id="container">
    <ul class="grid effect-2" id="grid">
        <?php foreach ($articles as $article) : ?>
            <li>
                <div class="image">
                    <a href="<?php echo $this->url('article', array('action' => 'detail', 'id' => $article->getId())) ?>">
                        <img src="<?php echo $this->basePath('/img/articles/'.$article->getPhoto()) ?>" alt="" />
                        <h2 class="gallery"><?php echo $article->getCompleteTitle(true) ?></h2>
                    </a>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
</div>

<script>
    var container = $('#container');
    // initialize
    container.masonry({
        columnWidth: 200,
        itemSelector: '.item'
    });
</script>

<script>
    new AnimOnScroll( document.getElementById( 'grid' ), {
        minDuration : 0.4,
        maxDuration : 0.7,
        viewportFactor : 0.2
    } );
</script>

<script type="text/javascript">
    // Auto semantic for text hovering images
    $(function() {
        $(".image").find("h2").wrapInner("<span>");
        $("h2 br").before("<span class='spacer'>").after("<span class='spacer'>");
    });
</script>