<?php

/**
 * @var Doctrine\Common\Collections\ArrayCollection $articles
 * @var Blog\Entity\Article $article
 */

?>

<ul class="grid effect-2" id="grid">
    <?php foreach ($articles as $article) : ?>
        <li>
            <div class="image">
                <a href="<?php echo $this->url('article', array('action' => 'detail', 'id' => $article->getId())) ?>">
                    <img src="<?php echo $this->basePath('/img/articles/'.$article->getPhoto1()) ?>"
                         alt="" class="img-polaroid-border-sm"/>
                    <h2 class="gallery"><?php echo $article->getCompleteTitle(true) ?></h2>
                </a>
            </div>
        </li>
    <?php endforeach ?>
    </ul>



<script>
    //whenTilesReady();

    function whenTilesReady() {
        var container = $('#container');
        // initialize
        container.masonry({
            columnWidth: 200,
            itemSelector: '.item'
        });
    }

</script>

<script>
    new AnimOnScroll( document.getElementById( 'grid' ), {
        minDuration : 0.2,
        maxDuration : 0.9,
        viewportFactor : 0.2
    } );
    // Auto semantic for text hovering images
    $(function() {
        $(".image").find("h2").wrapInner("<span>");
        $("h2 br").before("<span class='spacer'>").after("<span class='spacer'>");
    });
</script>