<?php

$title = 'Contactez moi';
$this->headTitle($title);

?>

<?php echo $this->partial('partial/flashmessenger') ?>


<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr class="short-hr"/>
            <h2 class="text-center"><?php echo $title ?></h2>
            <hr class="short-hr"/>

            <p class="text-center">
                <a href="mailto:fcaminade@hotmail.fr">Envoyez moi un mail !</a>
            </p>

        </div>
    </div>
</div>