<?php

/**
 * @var array $years
 * @var string $currentYear
 * @var array $tree
 * @var Blog\Entity\Article $article
 */

$title = 'Historique';
$this->headTitle($title);

?>

<?php echo $this->partial('partial/flashmessenger') ?>


<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr class="short-hr"/>
            <h2 class="text-center"><?php echo $title ?></h2>
            <hr class="short-hr"/>
        </div>

        <div class="row">
            <div class="col-lg-offset-3 col-lg-6 text-center">
                <ul class="nav nav-tabs nav-justified">
                    <?php foreach ($years as $year) : ?>
                        <li role="presentation" class="<?php echo $year == $currentYear ? 'active' : '' ?>">
                            <a class="h4" href="<?php echo $this->url('histo', array('year' => $year)) ?>">
                                <?php echo $year ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
    </div>

    <?php if (count($tree)) : ?>

        <?php foreach ($tree as $month => $articles) : ?>

            <div class="box">
                <div class="col-lg-12">
                    <hr class="short-hr"/>
                    <h2 class="text-center"><?php echo \Blog\Model\Calendar::getStaticMonthNames()[$month] ?></h2>
                    <hr class="short-hr"/>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $this->partial('blog/blog/partial/articles-list', array('articles' => $articles)) ?>
                    </div>
                </div>
            </div>

        <?php endforeach ?>

    <?php else : ?>

        <div class="box">
            <div class="row">
                <div class="col-lg-12">
                    <p class="text-center">
                        Aucun article à voir ici ! Circulez.
                    </p>
                </div>
            </div>
        </div>

    <?php endif ?>

</div>