<?php

/**
 * @var array $tree
 * @var array $allCategories
 * @var array $selectedCategories
 * @var Blog\Entity\Article $article
 */

use Blog\Entity\Article;

$title = 'Historique';
$this->headTitle($title);

$clickedCategories = json_encode($selectedCategories);
?>

<?php echo $this->partial('partial/flashmessenger') ?>


<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <h2 class="text-center"><?php echo $title ?></h2>
            <hr class="short-hr"/>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="box">
            <h5>Filtrer par catégories</h5>
            <ul class="list-unstyled">
                <?php foreach ($allCategories as $category) : ?>
                    <li>
                        <h3>
                            <span class="clickableCategory label <?php echo in_array($category, $selectedCategories) ? 'label-primary' : 'label-info' ?>">
                                <span class="category" data-category="<?php echo $category ?>">
                                    <?php echo Article::$categories[$category] ?>
                                </span>
                            </span>
                        </h3>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
    <div class="col-lg-9">
        <?php if (count($tree)) : ?>

            <?php foreach ($tree as $year => $articles) : ?>

                <div class="box">
                    <div class="col-lg-12">
                        <hr class="short-hr"/>
                        <h2 class="text-center"><?php echo $year ?></h2>
                        <hr class="short-hr"/>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">

                            <table class="table">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>Titre</th>
                                    <th>Date</th>
                                    <th>Catégorie</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($articles as $article) : ?>
                                    <tr>
                                        <td>
                                            <?php if ($article->getMainPicture()) : ?>
                                                <?php $picture = $article->getMainPicture() ?>
                                                <img src="<?php echo $picture->getFlickrUrl() ?>" width="50" height="50"
                                                     alt="<?php $article->getCompleteTitle() ?>" class="img-circle">
                                            <?php endif ?>
                                        </td>
                                        <td>
                                            <a class="silent"
                                               href="<?php echo $this->url('article', array('action' => 'detail', 'id' => $article->getId())) ?>">
                                                <?php echo $article->getCompleteTitle() ?>
                                            </a>
                                        </td>
                                        <td><?php echo $article->getDateFullString() ?></td>
                                        <td><?php echo $article->getCategoryLib() ?></td>
                                    </tr>
                                <?php endforeach ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            <?php endforeach ?>

        <?php else : ?>

            <div class="box">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="text-center">
                            Aucun article à voir ici ! Circulez.
                        </p>
                    </div>
                </div>
            </div>

        <?php endif ?>
    </div>

</div>

<script>
    var clickableCategories = $('.clickableCategory');

    clickableCategories.css('cursor', 'pointer');
    clickableCategories.css('user-select', 'none');

    clickableCategories.click(function() {
        var clickedCategories = <?php echo $clickedCategories ?>;
        var clickedCategory = $(this).find('span.category').data('category');

        var index = clickedCategories.indexOf(clickedCategory);
        if ((index > -1)) {
            // si category déjà selectionnée, on l'efface
            clickedCategories.splice(index, 1);
        } else {
            // sinon, on le sélectionne
            clickedCategories.push(clickedCategory);
        }

        var clickedCategoriesUrl = clickedCategories.join('+');
        if (clickedCategoriesUrl != '') {
            window.location.href = "<?php echo $this->url('histo') ?>/" + clickedCategoriesUrl;
        } else {
            window.location.href = "<?php echo $this->url('histo') ?>";
        }
    });
</script>