<?php

/**
 * @var Doctrine\Common\Collections\ArrayCollection $articles
 * @var Blog\Entity\Article $article
 */

$title = 'Accueil';
$this->headTitle($title);

?>

<?php echo $this->partial('partial/flashmessenger') ?>

<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <h2 class="text-center"><?php echo $title ?></h2>
            <hr class="short-hr"/>
            <?php if (count($articles)) : ?>
                <?php echo $this->partial('blog/blog/partial/articles-list') ?>
            <?php else : ?>
                <p class="text-center">
                    Aucun article à voir ici ! Circulez.
                </p>
            <?php endif ?>
            <hr class="short-hr"/>
        </div>
    </div>
</div>