<?php

/**
 * @var Doctrine\Common\Collections\ArrayCollection $articles
 * @var Doctrine\Common\Collections\ArrayCollection $tags
 * @var Blog\Entity\Article $article
 * @var Blog\Entity\Tag $tag
 * @var array $selectedTagNames
 */

$title = '#TAGS';
$this->headTitle($title);

$clickedTags = json_encode($selectedTagNames);
?>
<?php echo $this->partial('partial/flashmessenger') ?>


<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr class="short-hr"/>
            <h2 class="text-center"><?php echo $title ?></h2>
            <hr class="short-hr"/>

            <div class="row">
                <div class="col-lg-offset-1 col-lg-10 text-center">
                    <ul class="list-inline">
                        <?php foreach ($tags as $tag) : ?>
                            <li>
                                <h3>
                                    <span class="clickableTag label <?php echo in_array($tag->getTitle(), $selectedTagNames) ? 'label-primary' : 'label-info' ?>">
                                        #<span class="tagname"><?php echo $tag->getTitle() ?></span>
                                    </span>
                                </h3>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>

        </div>
    </div>
    <div class="box">
        <div class="col-lg-12">

            <?php if (count($articles)) : ?>

                <?php echo $this->partial('blog/blog/partial/articles-list') ?>

            <?php else : ?>

                <p class="text-center">
                    Sélectionnez des #Tags pour charger des articles
                </p>

            <?php endif ?>


        </div>
    </div>
</div>

<script>
    var clickableTags = $('.clickableTag');

    clickableTags.css('cursor', 'pointer');
    clickableTags.css('user-select', 'none');

    clickableTags.click(function() {
        var clickedTags = <?php echo $clickedTags ?>;
        var clickedTag = $(this).find('span.tagname').html();

        var index = clickedTags.indexOf(clickedTag);
        if ((index > -1)) {
            // si tag déjà selectionné, on l'efface
            clickedTags.splice(index, 1);
        } else {
            // sinon, on le sélectionne
            clickedTags.push(clickedTag);
        }

        var clickedTagsUrl = clickedTags.join('+');
        if (clickedTagsUrl != '') {
            window.location.href = "<?php echo $this->url('tags') ?>/" + clickedTagsUrl;
        } else {
            window.location.href = "<?php echo $this->url('tags') ?>";
        }
    });
</script>