<?php

/**
 * @var Doctrine\Common\Collections\ArrayCollection $articles
 * @var Doctrine\Common\Collections\ArrayCollection $tags
 * @var Blog\Entity\Article $article
 * @var Blog\Entity\Tag $tag
 */

$title = '#TAGS';
$this->headTitle($title);

?>
<?php echo $this->partial('partial/flashmessenger') ?>


<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr class="short-hr"/>
            <h2 class="text-center"><?php echo $title ?></h2>
            <hr class="short-hr"/>

            <div class="row">
                <div class=" col-lg-offset-3 col-lg-6 text-center">
                    <ul class="list-inline">
                        <?php foreach ($tags as $tag) : ?>
                            <li>
                                <h3>
                                    <span class="label label-info clickableTag">#<?php echo $tag->getTitle() ?></span>
                                </h3>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>

        </div>
    </div>
    <div class="box">
        <div class="col-lg-12">

            <?php if (count($articles)) : ?>

                <div id="articlesList">
                    <?php echo $this->partial('blog/blog/partial/articles-list') ?>
                </div>

            <?php else : ?>

                <p class="text-center">
                    Sélectionnez des #Tags pour charger des articles
                </p>

            <?php endif ?>

        </div>
    </div>
</div>

<script>
    var container = $('#container');
    // initialize
    container.masonry({
        columnWidth: 200,
        itemSelector: '.item'
    });
</script>

<script>
    new AnimOnScroll( document.getElementById( 'grid' ), {
        minDuration : 0.4,
        maxDuration : 0.7,
        viewportFactor : 0.2
    } );
</script>

<script type="text/javascript">
    // Auto semantic for text hovering images
    $(function() {
        $(".image").find("h2").wrapInner("<span>");
        $("h2 br").before("<span class='spacer'>").after("<span class='spacer'>");
    });
</script>

<script>

    var clickableTags = $('.clickableTag');

    clickableTags.css('cursor', 'pointer');
    clickableTags.css('user-select', 'none');

    clickableTags.click(function() {
        $(this).toggleClass('label-info').toggleClass('label-primary');
    })

</script>