<?php
/**
 * @var Zend\Form\Form $form
 */

$title = 'Connexion';
$this->headTitle($title);
?>

<div class="row">
    <h3>Connectez-vous à votre compte GG</h3>
</div>
<div class="row">
    <div class="card">

        <?php echo $this->partial('partial/flashmessenger') ?>

        <?php echo $this->form()->openTag($form) ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('nickname')) ?>
            <div class="col-md-8">
                <?php echo $this->formText($form->get('nickname')) ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('password')) ?>
            <div class="col-md-8">
                <?php echo $this->formPassword($form->get('password')) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-offset-4 col-md-8">
                <br/>
                <?php echo $this->formRow($form->get('submit')) ?>
            </div>
        </div>

        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<div class="links">
    <ul class="list-inline">
        <li><a href="<?php echo $this->url('blog') ?>">Consulter le Blog</a></li>
    </ul>
</div>